# SciPy

SciPy é uma coleção de algoritmos matemáticos e funções de conveniência construídas sob Numpy do Python. Ele adiciona poder significativo para a sessão interativa de Python, fornecendo ao usuário comandos e classes de alto nível para manipular e visualizar dados. Com o SciPy, uma sessão interativa de Python torna-se um ambiente de processamento de dados e prototipagem do sistema que rivaliza com sistemas como MATLAB, IDL, Octave, R-Lab e SciLab.

**coleção de algoritmos para álgebra linear, equações diferenciais, integração numérica, otimização, estatística e muito mais parte da stack SciPy construído em NumPy**

O benefício adicional de basar SciPy no Python é que isso também faz uma poderosa linguagem de programação disponível para o desenvolvimento de programas sofisticados e aplicativos especializados.

Tudo, desde programação paralela até sub-rotinas de base de dados e base de dados, foi disponibilizado ao programador Python. Todo esse poder está disponível além das bibliotecas matemáticas no SciPy.

Documentação https://www.scipy.org/scipylib/

Vamos focar muito mais nas matrizes NumPy, mas vamos mostrar algumas das capacidades do SciPy:

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

## Algebra Linear
**linalg**

In [3]:
from scipy import linalg

Determinante de uma matriz

In [4]:
# Calcule o determinante de uma matriz
linalg.det(A)

2.999999999999997

In [5]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

Calcule a decomposição de LU girada de uma matriz.

A decomposição é ::

    A = P L U

Onde P é uma matriz de permutação, L triangular inferior com elementos diagonais da unidade e U triangular superior.

In [6]:
P, L, U = linalg.lu(A)

In [7]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [8]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [9]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [11]:
np.dot( np.dot(P,L), U)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 8.]])

In [101]:
np.dot(L,U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

Podemos descobrir os autovalores e os vetores próprios desta matriz:

In [132]:
EW, EV = linalg.eig(A)

In [130]:
EW

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [131]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

**A solução de sistemas de equações lineares também pode ser feita:**

In [13]:
v = np.array([[0],[3],[5]])

In [15]:
v

array([[0],
       [3],
       [5]])

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [17]:
s = linalg.solve(A,v)

In [18]:
s

array([[ 3.],
       [-3.],
       [ 1.]])

## Álgebra Linear Esparsa
SciPy possui algumas rotinas para computação com matrizes esparsas e potencialmente muito grandes. As ferramentas necessárias estão no submodulo scipy.sparse.

* Uma matriz é dita esparsa quando possui uma grande quantidade de elementos com valor zero[1] (ou não presentes, ou não necessários).
* Existem diferentes métodos para criação de modelos de recomendação. O modelo criado na Neogrid foi baseado no algoritmo Factorization Machines, um modelo otimizado para trabalhar com matrizes esparsas e alto volume de dados, identificando padrões de comportamento e gerando projeções hipotéticas sobre cruzamentos que ainda não ocorreram.
* Matriz com dados escassos, para quem trabalha com text mining pode ser uma rotina. Por isso, existe maneiras de se trabalhar em Pyhton existe bibliotecas para se trabalhar nesse modelo, se chama sparce matrix.

Nós fazemos um exemplo sobre como construir uma matriz grande:

In [59]:
from scipy import sparse

In [60]:
A = sparse.lil_matrix((1000, 1000))

In [61]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [62]:
A[0,:100] = np.random.rand(100)

In [63]:
A[1,100:200] = A[0,:100]

In [64]:
A.setdiag(np.random.rand(1000))

In [65]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

**Algebra linear com matrizes esparsas**

In [66]:
from scipy.sparse import linalg

In [67]:
# Converte esta matriz para o formato linha esparsa comprimida.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [68]:
A = A.tocsr()

In [69]:
b = np.random.rand(1000)

In [70]:
b

array([1.67038170e-02, 2.01499763e-01, 3.84077874e-01, 3.70446238e-01,
       4.93578953e-01, 8.49973385e-01, 9.54712010e-01, 1.41296983e-01,
       7.57776401e-01, 8.11395657e-02, 7.69774549e-01, 8.61642976e-01,
       5.81676308e-01, 7.24991659e-02, 8.64189329e-01, 9.06425350e-01,
       5.25275595e-01, 5.56350076e-01, 6.27865102e-01, 6.27902335e-01,
       1.91640164e-01, 9.25917192e-01, 6.47509518e-01, 7.95927421e-01,
       2.91007914e-01, 9.45117798e-01, 5.08627800e-01, 1.04212548e-01,
       4.73032375e-01, 6.73629373e-02, 8.62844806e-01, 7.22662119e-01,
       3.56868537e-02, 9.13841896e-01, 2.99643759e-02, 1.35139262e-01,
       3.16599219e-01, 9.46733984e-03, 3.32527141e-01, 4.38643410e-01,
       9.12770187e-01, 1.49231734e-01, 2.47461620e-01, 7.24139241e-02,
       9.32544171e-01, 3.80439715e-01, 4.14962790e-01, 8.30574367e-04,
       6.02322482e-01, 4.26833102e-02, 9.56136707e-01, 6.80177389e-01,
       5.50911799e-01, 4.59544130e-01, 4.34063389e-01, 4.00647295e-01,
      

In [36]:
linalg.spsolve(A, b)

array([1.30567474e+01, 1.05272436e+01, 6.66284427e-01, 1.31397220e-01,
       2.61475334e+00, 3.04620649e+01, 1.42585000e+00, 8.44131960e-01,
       3.49540923e+00, 7.54576530e-01, 1.41798131e+00, 1.46380350e+00,
       1.00579104e+00, 6.25566259e+00, 4.86086281e-01, 6.16008191e-02,
       1.19202560e+00, 8.08429315e-01, 2.51806405e-01, 6.88658973e-01,
       1.56334030e-01, 2.99149362e-01, 5.08380317e-01, 8.71353394e-01,
       2.12513981e+00, 1.24170312e+00, 6.41673364e-01, 4.20359840e-01,
       1.25535385e+00, 2.82831191e+00, 2.78782606e-01, 5.59066178e-02,
       8.96641300e-01, 1.29339658e+00, 7.82901780e-01, 2.71585896e+00,
       3.81050923e+00, 2.63973019e-01, 2.80717961e+00, 9.15052836e-01,
       1.84727404e+00, 1.43562259e+00, 7.00727934e-01, 5.63853331e+00,
       1.25862867e+00, 2.40193802e-01, 1.12013300e+00, 2.24015389e+00,
       1.09671173e+00, 2.91749772e-02, 4.11066564e-01, 8.98575155e-01,
       3.75670994e-02, 7.70819081e-01, 9.87785394e-04, 8.77345936e+00,
      

Há muito mais que SciPy é capaz de, como Transformadas de Fourier, Funções de Bessel, etc ...

Dê uma olhada na Documentação para mais detalhes!